services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Rudak\JsInjector\:
    resource: '../../../src/*'
    exclude: '../../../src/{DependencyInjection,Resources}'

  Rudak\JsInjector\Harvester\ValuesHarvester:
    arguments:
      - !tagged_iterator rudak.injector

  Rudak\JsInjector\Harvester\DynamicValuesHarvester:
    arguments:
      - !tagged_iterator { tag: 'rudak.injector.dynamic', index_by: 'channel' }

  Rudak\JsInjector\EventListener\DynamicValuesListener:
    arguments:
      $scriptTagId: '%js_injector.dynamic_script_tag_id%'
      $enabled: '%js_injector.dynamic_enabled%'
      $logger: '@?logger'
    tags:
      - { name: kernel.event_subscriber }

  Rudak\JsInjector\Command\RudakGenerateJsCommand:
    arguments:
      $projectDir: '%kernel.project_dir%'
      $outputPath: '%js_injector.output_path%'
      $format: '%js_injector.format%'
      $namespace: '%js_injector.namespace%'
