services:

  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  Rudak\JsInjector\:
    resource: '../../../src/*'

  Rudak\JsInjector\Harvester\ValuesHarvester:
    arguments: [!tagged rudak.injector]