<?php

declare(strict_types=1);

namespace Rudak\JsInjector\Generator;

use Rudak\JsInjector\Validator\VariableNameValidator;

/**
 * Renders the JavaScript file content from the values to inject.
 *
 * Supports two output formats:
 *  - "module": an ES module that can be imported (`export default` / `export const`).
 *  - "globals": a classic script that assigns global variables.
 */
final class JsFileGenerator
{
    public const FORMAT_GLOBALS = 'globals';
    public const FORMAT_MODULE = 'module';

    private const JSON_OPTIONS = JSON_THROW_ON_ERROR;
    private const GLOBALS_CONSTANT = 'INJECTED_VALUES';

    /**
     * @param array<string, mixed> $values
     */
    public function generate(array $values, ?string $namespace = null, string $format = self::FORMAT_MODULE): string
    {
        if ([] === $values) {
            return '';
        }

        if (!in_array($format, [self::FORMAT_GLOBALS, self::FORMAT_MODULE], true)) {
            throw new \InvalidArgumentException(sprintf('"%s" is not a valid format', $format));
        }

        if (null !== $namespace && !VariableNameValidator::isValid($namespace)) {
            throw new \InvalidArgumentException(sprintf('"%s" is not a valid JavaScript namespace', $namespace));
        }

        $invalidKey = VariableNameValidator::findInvalidKey($values);
        if (null !== $invalidKey) {
            throw new \InvalidArgumentException(sprintf('"%s" is not a valid JavaScript variable name', $invalidKey));
        }

        $json = $this->encodeValues($values);

        if (self::FORMAT_MODULE === $format) {
            return $this->generateModule($namespace, $json);
        }

        return $this->generateGlobals($namespace, $json, array_keys($values));
    }

    private function generateModule(?string $namespace, string $json): string
    {
        $export = null !== $namespace
            ? sprintf('export const %s = %s;', $namespace, $json)
            : sprintf('export default %s;', $json);

        return sprintf("// generated by rudak:generate:js\n%s\n", $export);
    }

    /**
     * @param array<int, string> $keys
     */
    private function generateGlobals(?string $namespace, string $json, array $keys): string
    {
        if (null !== $namespace) {
            return sprintf(
                "// generated by rudak:generate:js\nvar %s = %s;\n",
                $namespace,
                $json
            );
        }

        $variableNames = implode(', ', $keys);

        return sprintf(
            "// generated by rudak:generate:js\nvar %s = %s;\n// creating %d variable(s)\nvar { %s } = %s;\n",
            self::GLOBALS_CONSTANT,
            $json,
            count($keys),
            $variableNames,
            self::GLOBALS_CONSTANT
        );
    }

    /**
     * @param array<string, mixed> $values
     *
     * @throws \JsonException
     */
    private function encodeValues(array $values): string
    {
        return json_encode($values, self::JSON_OPTIONS);
    }
}
